services:
  - type: web
    name: student-retention-ai
    rootDir: backend
    buildCommand: mkdir -p static && cp -r ../frontend/* static/ && pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
